In [12]:
#su paveldėjimu:
# Sukurkite klasę Vehicle su tokiais atributais - Pavadinimas, Rida
#Sukurkite išvestines klases Car, Bus, Train,
# kurie paveldėtų viską iš Vehicle, ir papildomai būtų galima
# nurodyti Seats - sėdimų vietų skaičių, ir visi 
# turėtų metoda GetSeats() grąžinantį tekstą:
# <Pavadinimas> turi <Seats> sėdimų vietų.

# class Vehicles():
#     def __init__(self, Pavadinimas, Rida):
#         self. Pavadinimas = Pavadinimas
#         self.Rida = Rida

# class Car(Vehicles): # isirasom () tevines klases pavadinima
#     def __init__(self, Pavadinimas, Rida, Seats):  # kintamuosius isirasome, tai ka paveldejom + naujas sios klases
#         super().__init__(Pavadinimas, Rida)# kintamuosius isirasome, tai ka paveldejom
#         self.Seats = Seats # isirasome trukstama kintamaji

#     def GetSeats(self):
#         Txt = self.Pavadinimas + "turi "+ str(self.Seats) + " sedimu vietu."
#         return Txt
    
# class Bus(Vehicles): 
#     def __init__(self, Pavadinimas, Rida, Seats):  
#         super().__init__(Pavadinimas, Rida)
#         self.Seats = Seats 

#     def GetSeats(self):
#         Txt = self.Pavadinimas + "turi "+ str(self.Seats) + " sedimu vietu."
#         return Txt
    
# class Train(Vehicles): 
#     def __init__(self, Pavadinimas, Rida, Seats):  
#         super().__init__(Pavadinimas, Rida)
#         self.Seats = Seats 

#     def GetSeats(self):
#         Txt = self.Pavadinimas + "turi "+ str(self.Seats) + " sedimu vietu."
#         return Txt
# transporto_priemones = Car(Pavadinimas = "Audi ", Rida = 25300, Seats = 4)
# print(transporto_priemones.GetSeats())
# transporto_priemones = Bus(Pavadinimas = "Man Busses", Rida = 300, Seats = 55)
# print(transporto_priemones.GetSeats())
# transporto_priemones = Train(Pavadinimas = "Train Company ", Rida = 0, Seats = 300)
# print(transporto_priemones.GetSeats())

Audi turi 4 sedimu vietu.
Man Bussesturi 55 sedimu vietu.
Train Company turi 300 sedimu vietu.


In [ ]:
# NUMPY MOBULIS

In [13]:
x = [1,2,3,4,5]

naujas_x =[]
for skaicius in x:
    naujas_x.append(skaicius-0.75)
print(naujas_x)

[0.25, 1.25, 2.25, 3.25, 4.25]


In [14]:
import numpy as np # importavosm numpy biblioteka

In [20]:
# array (masyvai)
x = np.arange(0,10) #arange funkcija, galima nurodyti ir zingsni (0,10,3)
print(x) # isspausdina be kableliu, reiskia tai numpy masyvas
print(type(x)) # ripas- masyvas

[0 2 4 6 8]
<class 'numpy.ndarray'>


In [21]:
y = x-0.75
print(y)

[-0.75  1.25  3.25  5.25  7.25]


In [ ]:
np.average()
np.min()
np.mean()
np.median()

In [22]:
a_list = [i for i in range(1,11)] # bus sarasas
print(a_list)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [25]:
a_array = np.asarray(a_list) # konvertuoja pitono sarasa i masyva, su kuriuo galima atlikineti matematinius veiksmus
print(a_array+0.75)

[ 1.75  2.75  3.75  4.75  5.75  6.75  7.75  8.75  9.75 10.75]


In [27]:
x = [1,2,3] # turi buti vienodsa elementu kiekis, kitaip neveiks
y = [1,4,5]
# norint sudauginti sarasu skaicius viena su kitu
x_np = np.asarray(x)
y_np = np.asarray(y)
c = x_np*y_np
print(c)

[ 1  8 15]


In [31]:
np.min(x)
np.max(x)
np.median(x)

2.0

In [32]:
atsitiktinis = np.random.randint(0,10,100) # np - modulis, random - moduliukas, randint -
print(atsitiktinis) # sugeneruoja kiek elementu nori, siuo atveju nuo 1 iki 10 simta random elementu

[3 9 7 0 4 7 3 5 4 1 1 0 0 5 1 5 0 5 7 0 4 1 0 6 0 4 6 3 4 8 3 0 0 8 1 3 6
 0 5 1 1 7 9 2 4 3 9 2 5 5 3 3 6 0 6 5 7 6 1 8 3 5 5 9 8 9 7 6 2 2 0 6 5 3
 4 6 4 2 5 2 4 9 0 6 6 9 0 1 0 8 0 5 7 4 8 8 5 2 8 0]


In [34]:
atstitiktitnis_float = np.random.rand(10) # jei naudojam rand- bus skaiciai nuo 0 iki 1, gali kartotis; randint jau butina nurodyti rezi skaiciu
print(atstitiktitnis_float)

[0.83644469 0.4726832  0.48479838 0.16269632 0.38416868 0.59689948
 0.30337495 0.83014002 0.16950161 0.67993365]


In [67]:
xas = np.random.randint(1,10,100)
svoriai = np.random.rand(100)
# mean in average- mean skaiciuoja vidurki

vidurkis = np.mean(xas) # grieztai aritmetinis vidurkis
print(vidurkis) # kas kart printinant skirsis ats, nes kas kart generuojami vis kiti random skaiciai
sv_vid = np.average(xas) # vidurkis atsizvelgiant i svorius
print(sv_vid)
sv_vid = np.average(xas, weights = svoriai)
print(sv_vid)


# median()
medx = np.median(xas)
print(medx)
print(medx, np.min(xas), np.max(xas))

5.16
5.16
5.217306832020242
5.0
5.0 1 9


In [78]:
# linspace funkcija (linear space)
#nurodomas startas ir stopas ir kiek skaiciu norima gauti, zingsnis pasirenkamas pagal default formule

l = np.linspace(0,10,11) # skaiciai skiriasi, nes juos delioja vienodais atstumais tieseje, paskaiciuoja pats zingsni
print(l)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [85]:
# asarray, arange, min, max, mean, average, median
n_np = np.arange(0,10)
# kaip metodai:
minn = n_np.min()
print(minn)

print(n_np.mean()) # aritmetinis vidurkis

# n_np.median() # medianai neveikia metodas, nerealizuotas, reikia naudoti kaip funkcija

print(n_np.max())

0
4.5
9


In [2]:
%load_ext autoreload
%autoreload 2
import modulis

In [3]:
print(modulis.A)

55


In [4]:
modulis.printA()

As esu nauja PrintA() funkcija
Dar vienas paskutinis pakeitimas


In [5]:
# iškelkite savo anksčiau rašytas Vehicle, Car, etc klases
# į modulį
# ir patikrinkite klasių veikimą
# sukurdami kintamuosius ir patikrindami jų veikimą

transporto_priemones = modulis.Car(Pavadinimas = "Ford ", Rida = 2300, Seats = 6)
print(transporto_priemones.GetSeats())
transporto_priemones = modulis.Bus(Pavadinimas = "Double Decker ", Rida = 500000, Seats = 135) # butina pries klases pavadinima parasyti modulio pavadinima, kitaip neveiks
print(transporto_priemones.GetSeats())
transporto_priemones = modulis.Train(Pavadinimas = "Traukinukas Tomas ", Rida = 5965210, Seats = 300)
print(transporto_priemones.GetSeats())

Ford turi 6 sedimu vietu.
Double Decker turi 135 sedimu vietu.
Traukinukas Tomas turi 300 sedimu vietu.


In [46]:
#sukurkite failus nuskaitančią klasę, ji turi būti aprašyta jūsų kuriamame modulyje;
#ta klasė turi nuskaityti pateiktą failą, ir suskaidyti stulpelius į sąrašus:
#sąrašai I, U, j, P, duomenys iš juos iš atitinkamų taip pat pavadintų stulpelių
#realizuokite tai, jog klasė rastų tokį dydį - maksimalų P, suskaičiuotų tokį dydį pce = Pmax / 1000 * 100%;
#šie dydžiai turi būti pasiekiamį arba kaip atributas, arba galite įdėti metodą jam gauti

#pilnas sprendimas, su pasitikrinimo printais
# class keturiolika_failu():
#     def __init__(self, Pavadinimas, Skirtukas):
#         self.Pavadinimas = Pavadinimas
#         self.Skirtukas = Skirtukas
#         self.I = []
#         self.U = []
#         self.j = []
#         self.p = []

#     def dataReader(self):
#         fname = self.Pavadinimas
#         file = open(fname, mode='r', encoding= 'utf-8')
#         sarasas = file.readlines() # suformuoja teksta kaip eiluciu sarasa
#         file.close()
#         print(sarasas) # pasitikrinam ar veikia

#         for eilute in sarasas[1::]:
#             self.I.append(float(eilute.split(self.Skirtukas)[0]))
#             self.U.append(float(eilute.split(self.Skirtukas)[1]))           
#             self.j.append(float(eilute.split(self.Skirtukas)[2]))
#             self.p.append(float(eilute.split(self.Skirtukas)[3].replace('\n', '')))
#         print(self.I)
#         print(self.U) 
#         print(self.j) 
#         print(self.p) 

#     def getPmax(self):
#         Pmax = (max(self.p))
#         return Pmax
    
#     def getPCE(self):
#         Pmax= self.getPmax()
#         PCE = round((Pmax / 1000 * 100),2)
#         return PCE
    
# sarasas = keturiolika_failu('REF_D_5k_FW_2.03.dat', ';') #pasitikrinam ar nuskaito info is failo
# sarasas.dataReader()
# print(sarasas.getPCE())

['U[V] ; I[A] ; j[mA/cm^2] ; P[mW/cm^2]\n', '1.2 ; 0.0010878 ; 13.59755 ; 16.31706\n', '1.1766667 ; 0.0008779 ; 10.9735512 ; 12.912212\n', '1.1533333 ; 0.000675 ; 8.4376562 ; 9.7314302\n', '1.13 ; 0.0004624 ; 5.780055 ; 6.5314621\n', '1.1066667 ; 0.0002595 ; 3.2442637 ; 3.5903185\n', '1.0833333 ; 7.83e-05 ; 0.9787641 ; 1.0603278\n', '1.06 ; -7.92e-05 ; -0.9902056 ; -1.049618\n', '1.0366667 ; -0.0002111 ; -2.63856 ; -2.7353072\n', '1.0133333 ; -0.0003275 ; -4.0936325 ; -4.1482143\n', '0.99 ; -0.0004257 ; -5.3214875 ; -5.2682726\n', '0.9666667 ; -0.0005053 ; -6.3163262 ; -6.105782\n', '0.9433333 ; -0.0005775 ; -7.2184413 ; -6.8093962\n', '0.92 ; -0.0006322 ; -7.9018762 ; -7.2697261\n', '0.8966667 ; -0.0006841 ; -8.55161 ; -7.6679436\n', '0.8733333 ; -0.0007236 ; -9.0446012 ; -7.8989518\n', '0.85 ; -0.0007626 ; -9.5324562 ; -8.1025878\n', '0.8266667 ; -0.0007935 ; -9.9188812 ; -8.1996085\n', '0.8033333 ; -0.00082 ; -10.2496088 ; -8.2338524\n', '0.78 ; -0.000844 ; -10.54984 ; -8.2288752\n'

In [97]:
sarasas = modulis.keturiolika_failu('REF_D_5k_FW_2.03.dat', ';')
sarasas.dataReader()
print(sarasas.getPCE())

1.63


In [104]:
#sukurkite failus nuskaitančią klasę, ji turi būti aprašyta jūsų kuriamame modulyje;
#ta klasė turi nuskaityti pateiktą failą, ir suskaidyti stulpelius į sąrašus:
#sąrašai I, U, j, P, duomenys iš juos iš atitinkamų taip pat pavadintų stulpelių
#realizuokite tai, jog klasė rastų tokį dydį - maksimalų P, suskaičiuotų tokį dydį pce = Pmax / 1000 * 100%;
#šie dydžiai turi būti pasiekiamį arba kaip atributas, arba galite įdėti metodą jam gauti

class keturiolika_failu():
    def __init__(self, Pavadinimas, Skirtukas):
        self.Pavadinimas = Pavadinimas
        self.Skirtukas = Skirtukas
        self.I = []
        self.U = []
        self.j = []
        self.p = []
        self.dataReader() # kreipiasi i dataReader

    def dataReader(self):
        fname = self.Pavadinimas
        file = open(fname, mode='r', encoding= 'utf-8')
        sarasas = file.readlines()
        file.close()

        for eilute in sarasas[1::]:
            self.I.append(float(eilute.split(self.Skirtukas)[0]))
            self.U.append(float(eilute.split(self.Skirtukas)[1]))           
            self.j.append(float(eilute.split(self.Skirtukas)[2]))
            self.p.append(float(eilute.split(self.Skirtukas)[3].replace('\n', '')))

    def getPmax(self):
        Pmax = (max(self.p))
        return Pmax
    
    def getPCE(self):
        Pmax= self.getPmax()
        PCE = round((Pmax / 1000 * 100),2)
        return PCE
    
sarasas = keturiolika_failu('REF_D_5k_FW_2.03.dat',';')
# sarasas.dataReader()
print(sarasas.getPCE())

1.63


In [ ]:
#__ padaro metoda privaciu ir kitas naudotojas negali juo pasinaudoti, kol pas nenuimsi __
class keturiolika_failu():
    def __init__(self, Pavadinimas, Skirtukas):
        self.Pavadinimas = Pavadinimas
        self.Skirtukas = Skirtukas
        self.I = []
        self.U = []
        self.j = []
        self.p = []
        self.__dataReader() # kreipiasi i dataReader; __ padaro privaciu ir naudojami tik klases viduje

    def __dataReader(self):
        fname = self.Pavadinimas
        file = open(fname, mode='r', encoding= 'utf-8')
        sarasas = file.readlines()
        file.close()

        for eilute in sarasas[1::]:
            self.I.append(float(eilute.split(self.Skirtukas)[0]))
            self.U.append(float(eilute.split(self.Skirtukas)[1]))           
            self.j.append(float(eilute.split(self.Skirtukas)[2]))
            self.p.append(float(eilute.split(self.Skirtukas)[3].replace('\n', '')))

    def getPmax(self):
        Pmax = (max(self.p))
        return Pmax
    
    def getPCE(self):
        Pmax= self.getPmax()
        PCE = round((Pmax / 1000 * 100),2)
        return PCE
    
sarasas = keturiolika_failu('REF_D_5k_FW_2.03.dat',';')
# sarasas.__dataReader()
print(sarasas.getPCE())

In [ ]:
# Mantvydo pvz:
#sukurkite failus nuskaitančią klasę, ji turi būti aprašyta jūsų kuriamame modulyje;
#ta klasė turi nuskaityti pateiktą failą, ir suskaidyti stulpelius į sąrašus:
#sąrašai I, U, j, P, duomenys iš juos iš atitinkamų taip pat pavadintų stulpelių
#realizuokite tai, jog klasė rastų tokį dydį - maksimalų P, suskaičiuotų tokį dydį pce = Pmax / 1000 * 100%;
#šie dydžiai turi būti pasiekiamį arba kaip atributas, arba galite įdėti metodą jam gauti

class Txtreader:
    def __init__(self, failopavadinimas):
        self.failopavidinimas = failopavadinimas
        self.I = []
        self.U = []
        self.j = []
        self.P = []
    
    def skaitytojas(self):
        failas = open(self.failopavidinimas, mode= "r")
        tekstas = failas.readlines()
        failas.close()
        for eilute in tekstas[1:]:
            u =float(eilute.split(";")[0])
            self.U.append(u)
            i =float(eilute.split(";")[1])
            self.I.append(i)
            J =float(eilute.split(";")[2])
            self.j.append(J)
            p =float(eilute.split(";")[3])
            self.P.append(p)
    def maksimalusP(self):
        maximumas = max(self.P)
        return maximumas
    
    def pce(self):
        maximumas = self.maksimalusP()
        ats = maximumas / 1000 * 100
        return ats
    

kintamasis = Txtreader("REF_D_1k_FW_2.05.dat")
kintamasis.skaitytojas()
kintamasis.maksimalusP()
kintamasis.pce()
import modulis


kintamasis = modulis.Txtreader("REF_D_1k_FW_2.05.dat")
kintamasis.skaitytojas()
kintamasis.maksimalusP()
kintamasis.pce()

In [108]:
import pandas as pd

In [107]:
pip install pandas

Defaulting to user installation because normal site-packages is not writeable
  Using cached pandas-2.2.1-cp312-cp312-win_amd64.whl.metadata (19 kB)
   ---------------------------------------- 0.0/11.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.5 MB 393.8 kB/s eta 0:00:30
   ---------------------------------------- 0.1/11.5 MB 804.6 kB/s eta 0:00:15
   - -------------------------------------- 0.3/11.5 MB 1.6 MB/s eta 0:00:08
   - -------------------------------------- 0.5/11.5 MB 2.0 MB/s eta 0:00:06
   --- ------------------------------------ 0.9/11.5 MB 3.1 MB/s eta 0:00:04
   -------- ------------------------------- 2.4/11.5 MB 6.9 MB/s eta 0:00:02
   --------------- ------------------------ 4.4/11.5 MB 10.7 MB/s eta 0:00:01
   -------------------- ------------------- 5.8/11.5 MB 12.3 MB/s eta 0:00:01
   ----------------

In [109]:
pip install matplotlib

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [110]:
import matplotlib.pyplot as plt

In [111]:
import pandas as pd